---
- name: Delete index.html file
  file:
    path: /var/www/html/index.html
    state: absent
- name: Upload application file
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    mode: 0755
  notify:
    - Restart Apache
