---
- name: Install packages
  apt:
    name:
      - python-pymysql
      - mysql-server
      - python3-mysqldb
    update_cache: yes
    cache_valid_time: 3600
    state: present

- name: Start and enable MySQL service
  service:
    name: mysql
   state: started
    enabled: true
 
